### ISSUE TITLE
Error while loading weights

### ISSUE THREAD

**Issue by asad1996172** [siavash9000/im2txt_demo#3]
I am somehow unable to pull the weights using lfs. So please kindly guide me where to put them. because i tried to put them in im2txt_demo/im2txt_pretrained but i get the following error.

DataLossError (see above for traceback): Unable to open table file /root/im2txt_pretrained/model.ckpt-2000000: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_171 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_171/tensor_names, save/RestoreV2_171/shape_and_slices)]]

**Comment by siavash9000** [comment]
Hello Asad,
what message do you get when you execute `git lfs pull` in the repo folder? I guess the github data quota is already reached for this month ...
best regards,
Siavash

**Comment by asad1996172** [comment]
Hello,
I have solved that issue . Now i am facing this one

NotFoundError (see above for traceback): Tensor name "lstm/basic_lstm_cell/bias" not found in checkpoint files /home/asadmahmood72/Image_to_text/models/im2txt/model.ckpt-2000000
[[Node: save/RestoreV2_380 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_380/tensor_names, save/RestoreV2_380/shape_and_slices)]]

My os is UBUNTU 16.04
my tensorflow version is 1.2.0
@siavash9000  help me

**Comment by siavash9000** [comment]
I am not sure that you really have the model files. The error message says that the model could not be loaded correctly. Please verify that that you have the correct model file. The file `model.ckpt-2000000 `should be 142 mb and should be in the folder `im2txt_pretrained`. If the file is not correct you can download the needed model files here:
https://drive.google.com/file/d/0Bw6m_66JSYLlRFVKQ2tGcUJaWjA/view and here
https://drive.google.com/file/d/0Bw6m_66JSYLleHdDNmpndjNPVDg/view?usp=sharing

The problem is probably caused by the github lfs data quoata (https://help.github.com/articles/about-storage-and-bandwidth-usage/). The easiest solution is to wait for the next month, since the quoata is reseted every month. Then you can download the models easily by the usage of the command `git lfs pull`

**Comment by asad1996172** [comment]
Well That is fine.. i checked it. Can you tell me that these weights were obtained by training the model using which tensorflow version?
@siavash9000

**Comment by siavash9000** [comment]
Do you use the Dockerfile? The Dockerfile sets up Tensorflow 0.12.1 which should fit to the model.

**Comment by asad1996172** [comment]
yup it worked..

**Comment by jmfu95** [comment]
@asad1996172  i got the same error with you.

DataLossError (see above for traceback): Unable to open table file /root/im2txt_pretrained/model.ckpt-2000000: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_382 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_382/tensor_names, save/RestoreV2_382/shape_and_slices)]]

 How did  you solve this?Could yo guide me?I would be grateful .
