### ISSUE TITLE
./process_image.sh: line 21: im2txt/bazel-bin/im2txt/run_inference: Permission denied.Could someone know？

### ISSUE THREAD

**Issue by jmfu95** [siavash9000/im2txt_demo#5]
hello,i follow the instructions and  complete the previous steps.but when i run the last step "./process_image.sh imgs/bikes.jpg",it has problems. 
problems belows：
./process_image.sh: line 21: im2txt/bazel-bin/im2txt/run_inference: Permission denied.
Could someone know?
i tried chmod 777 process_image.sh,but it not work.
@siavash9000 Could you help me?I would be grateful.

**Comment by siavash9000** [comment]
Hello,
I always ask this first since it is most often the problem: have you downloaded the models correctly?
The command `git lfs pull`  can fail due to githubs limited free lfs tier.
You can verify by performing `ls -lah` in folder `im2txt_pretrained`. The file `model.ckpt-2000000` should have a size of 143 mb.

Do you run the command `./process_image.sh imgs/bikes.jpg` inside the running docker container? You should have root priviliges inside the container, so that no permission problem should happen.

**Comment by siavash9000** [comment]
I assume this related to 
https://github.com/siavash9000/im2txt_demo/issues/6
, so I close this issue. Please reopen if the problem persists or a new one occures.
