### ISSUE TITLE
LFS Pull Failed

### ISSUE THREAD

**Issue by andrewb-ms** [siavash9000/im2txt_demo#8]
**$ git lfs pull** gives this:

```
Git LFS: (0 of 1 files) 0 B / 142.18 MB                                                                                                                                     
batch response: This repository is over its data quota. Purchase more data packs to restore access.
```

**Comment by siavash9000** [comment]
Hi andrewb-ms,
sorry that git lfs does not work now. The lfs feature is unfortunately not free and the free quota is used very quick. The section Limitations has a guide how to download the models manually. I have added the error message in this section so that it is easier to spot for you. 
Best regards,
Siavash

**Comment by andrewb-ms** [comment]
Thanks.  That worked!
